(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (display-error amount)
    "Incorrect password")
  (let ((password-list (list password)))
    (define (mkj new-password)
      (set! password-list (cons new-password password-list))
      dispatch)
    (define (dispatch p m)
      (if (memq p password-list)
          (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                ((eq? m 'make-joint) mkj)
                (else (error "Unknown request -- MAKE-ACCOUNT"
                             m)))
          display-error))
    dispatch))

(define (make-joint account old-password new-password)
  ((account old-password 'make-joint) new-password))
